### ISSUE TITLE
Works on Windows?

### ISSUE THREAD

**Issue by hoegge** [watilde/tvm#43]
Installed TVM which looked good, but dosn't it work on Windows? It downloads the versions well, but there seems to be no way to run tsc using TVM. If I enter `tvm tsc .` it just answers: `tvm use <version>`

**Comment by watilde** [comment]
Have you ran `tvm use` first and then ran `tvm tsc`? You need to specify the version you'd like to use.

**Comment by hoegge** [comment]
Yes. Install and use works fine. 

Best
Hoegge

**Comment by jitterbox** [comment]
I'm having issues with it on Windows as well... fails on 'cp' command when running `npm install <version>`:
```
'cp' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cp -r XXXXXconfig/../../src/v3.5.3/typescript-3.5.3 XXXXXconfig/../../typescript/v3.5.3'
```
